name: "TextNow Autosend"
on:
  push: # 触发机制为push操作
    branches: main
  schedule: # 触发机制为定时任务utc
    - cron: "35 8 * * *" # 每天8点35分自动执行
    - cron: "20 10 * * *" # 每天10点20分自动执行
    - cron: "12 13 * * *" # 每天13点12分自动执行
    - cron: "45 15 * * *" # 每天15点45分自动执行
    - cron: "06 18 * * *" # 每天18点06分自动执行
jobs:
  autosend:
    runs-on: ubuntu-latest # 运行环境为最新的Ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # 使用官方提供的checkout 2.0版本获取代码
      - name: Setup node.js
        uses: actions/setup-node@v1 # 使用官方提供的setup-node 1.0版本配置node环境
        with:
          node-version: "12.x" # 使用node 12版本作为运行环境
      - name: Install dependencies
        run: npm install # 安装依赖
      - name: Run autosend
        env:
          TEXTNOW_USERNAME: ${{secrets.TEXTNOW_USERNAME}} # 获取并设置定义好的用户名环境变量值
          TEXTNOW_PASSWORD: ${{secrets.TEXTNOW_PASSWORD}} # 获取并设置定义好的用户密码环境变量值
          TEXTNOW_RECIPIENT: ${{secrets.TEXTNOW_RECIPIENT}} # 获取并设置定义好的接收方的电话号码环境变量值
          TEXTNOW_MESSAGE: ${{secrets.TEXTNOW_MESSAGE}} # 获取并设置定义好的发送的信息内容环境变量值
          TEXTNOW_COOKIES: ${{secrets.TEXTNOW_COOKIES}}
        run: |
          set -x
          rm -f news
          wget https://www.bbc.com/news -O news
          sed -ri -e '/most-popular-read/!d' news
          sed -ri -e 's@<li@\n\0@g' news
          sed -ri -e 's@>([0-9]+|Most read)<@@g' news
          sed -ri -e 's@<[^>]*>@@g' news
          sed -ri -e 's@&#(x[0-9]+);@\\\1@g' news
          sed -ri -e '/^$/d' news
          num=$(expr $RANDOM % 8 + 1)
          TEXTNOW_MESSAGE=$(head -n $num news| tail -n 1)
          TEXTNOW_MESSAGE=$(printf "$TEXTNOW_MESSAGE")
          rm -f news
          [ -n "$TEXTNOW_MESSAGE" ] || exit 0
          if [ "${TEXTNOW_COOKIES}" == "" ]; then node index.js; exit 0; fi
          main() {
            set -e
            let count=1
            for i in "$@"; do
              echo Start account: $count....
              TEXTNOW_COOKIES="$i" node index.js;
              let count+=1
            done
          }
          eval main $(sed 's/^/"/g;s/$/"/g;s/|+|/" "/g'<<<${TEXTNOW_COOKIES})
